services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wam
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  whacameal_web:
    build: .
    container_name: whacameal_web
    restart: unless-stopped
    ports:
      - "3003:3000"
    depends_on:
      - postgres
      - mailhog
