import { findAccountById } from "@/actions/account/find-account-by-id.action";
import Navbar from "@/components/navbar";
import type { Metadata } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: ReactNode }>) {
  const session = undefined;
  const user = session ? await findAccountById(session.user.id) : null;
  return (
    <>
      {session && <Navbar user={user} />}
      {children}
    </>
  );
}
