import Navbar from "@/components/navbar";
import type { Metadata } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: ReactNode }>) {
  return (
    <div className="space-y-4">
      <Navbar />
      <div className="container mx-auto">{children}</div>
    </div>
  );
}
