import { auth } from "@/auth";
import Navbar from "@/components/navbar";
import { findById } from "@/data/user.data";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { ReactNode } from "react";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{ children: ReactNode; }>) {
    const session = await auth();
    const user = session ? await findById(session.user.id) : null;
    return (
        <>
            <SessionProvider>
                <Navbar user={user} />
                {children}
            </SessionProvider>
        </>
    );
}
